### ISSUE TITLE
자료 수정

### ISSUE THREAD

**Issue by lee-sj** [hufslion/hufslion.github.io#103]
@eunjin97 자료에 문제가 있어서 정상작동하지 않습니다. 수정해주세요 수정 수정 수정

**Comment by eunjin97** [comment]
어떤 것 말씀하시는 거에요?? ppt요??

**Comment by lee-sj** [comment]
사이트 확인하시면 게시글이 안나와요 커밋아래 x표시뜨고 정상커밋이아니네요

**Comment by eunjin97** [comment]
새로 수정했습니다! 근데 global에 test에는 잘 나오는데 hufslion에만 안 올라가는데 혹시 왜그런지 알려주실 수 있을까요..ㅠㅠㅠ

**Comment by eunjin97** [comment]
어제 새로 커밋했는데 그것도 정상커밋이 아닌가요??ㅠㅠㅠ..

**Comment by lee-sj** [comment]
커밋 확인하고 제작자 분이 수정하는게 아닐까요? 커밋에서 뭔 에러 있다고 메시지 확인하세요
제가 만든게 아니라 저도 잘 모르겠네요

**Comment by lee-sj** [comment]
tag empty 184 ~~ 메세지 확인하고 수정해주세요 몇일째 자료 배포가 안되고 있네요 해당 자료때문에

**Comment by eunjin97** [comment]
아 죄송합니다ㅠㅠ.. 제가 커밋확인하는 것에 미숙해서 어디서 오류가 생겼는지 헤매고 있었어요ㅠㅠㅠ..!! 그래서 새로 커밋하고 그랬는데ㅠㅠ.. 이제 확실히 알겠습니다!! 배포되는 것까지 확인했습니다!! 죄송합니다ㅠㅠㅠ

**Comment by eunjin97** [comment]
저 때문에 안 됐던 것 다시 커밋해서 정상 커밋 되는 것 확인했습니다!! 모두께 민폐끼쳐 죄송합니다ㅠㅠㅠ

**Comment by lee-sj** [comment]
고생 많았어유 확인!!
