### ISSUE TITLE
OT 자료 업로드 바람(기중_교육팀장)

### ISSUE THREAD

**Issue by lee-sj** [hufslion/hufslion.github.io#11]
3월 1일 까지 OT 자료 
카테고리 세션으로 작성해서 풀리퀘스트 보내주세요

**Comment by meuheuhe** [comment]
ot자료 다음주까지 해도 괜찮을까

2019년 2월 24일 (일) 오후 5:21, leesj <notifications@github.com>님이 작성:

**Comment by lee-sj** [comment]
언제까지 가능한가요

**Comment by lee-sj** [comment]
@meuheuhe 자세한 업로드 일정 comment 로 남겨주세요 ( 진행상황을 모두가 알수있게 해주세요 )

**Comment by meuheuhe** [comment]
ot ppt는 월요일 까지 만들어서 올리려고 합니다

2019년 2월 28일 (목) 오후 3:43, leesj <notifications@github.com>님이 작성:

**Comment by meuheuhe** [comment]
https://github.com/hufsglobal/hufsglobal.github.io/blob/master/_posts/test/OT%20-%20prod.%EA%B8%B0%EC%A4%91.md
앞으로 사용할 ppt템플릿에 적용시켜 ot ppt만들어 보았습니다. 포인트 제도 같은경우는 따로 깔끔하게 만들어서 사진으로 올릴 예정입니다. 필요한 부분이 있으면 피드백 주시길

**Comment by lee-sj** [comment]
ppt 4 공식 후원사 로고만 넣으면 좋을것 같습니다. ( 크레딧 나오는지 확실하지않음 )
ppt 7 해당 링크는 자료준비를 위한 테스트 서버입니다. 학교 사이트로 링크 교체해주세요
ppt 9 링크 말고 멋사 드라이브에 업로드 예정 으로 문구 교체 해주세요

ppt 템플릿 이걸로 가는걸로 정보팀장과 논의하신건가요? 

ot 는 따로 텍스트 자료 필요없을것 같습니다. 
자료 업로드할때는 세션 1 자료 하단부 참고해서 ppt 다운로드 링크로 대체 해주세요

**Comment by meuheuhe** [comment]
템플릿은 이거로 사용하기로 하였고 수정할 부분 수정하고 세션1참고해서 한 번에 올리겠습니다

2019년 3월 5일 (화) 12:22, leesj <notifications@github.com>님이 작성:

**Comment by meuheuhe** [comment]
요청하신 부분 수정하였고, 자료 pr 합니다.

**Comment by lee-sj** [comment]
예 pr에서 이어서 코멘트하겠습니다 이슈 닫습니다.
