### ISSUE TITLE
예비 세션 자료 업로드 기한 (교육 운영진 5인)

### ISSUE THREAD

**Issue by lee-sj** [hufslion/hufslion.github.io#12]
예비 세션을 준비하는 운영진 5인 
카테고리는 session 입니다. 

[ 자료 업로드 기한]
중간고사 전 대비를 위한 2인 먼저 1주차 전까지 제출
남은 3인은 세션_8 전까지 제출 

에 대한 의견 comment로 주세요

**Comment by hyojin17** [comment]
세션_8전까지 제출 의견 동의합니다.1

**Comment by dlrytnwkd** [comment]
세션_8 전까지면 8일 전까지라는 뜻인가요?

**Comment by lee-sj** [comment]
@dlrytnwkd 세션시트 상단부에 세션 번호가있습니다

**Comment by lee-sj** [comment]
내일까지 정오까지 의견이나 다른 사항 없다면 1주차 전까지 예비 세션자료 만들사람과 늦게 만들사람 제가 지정해서 전달하겠습니다. @bbj0423 @seungyuns @eunjin97

**Comment by lee-sj** [comment]
예비 세션 제출 기한 
세션 1 까지 제출 2인 : 윤서 승윤
세션 8 까지 제출 3인 : 태훈 효진 은진 
@hyojin17 @dlrytnwkd @bbj0423 @seungyuns @eunjin97

**Comment by lee-sj** [comment]
윤서 승윤이 세션 8근처에서 세션이 있고 효진 은진이 세션 1근처에 본인 세션이 있어서 이렇게 배치 하였습니다. ㅎㅎ

**Comment by eunjin97** [comment]
저도 동의합니다.

Windows 10용 메일에서 보냄

보낸 사람: hyojin17
보낸 날짜: 2019년 2월 26일 화요일 오후 5:34
받는 사람: hufslion/hufslion.github.io
참조: eunjin97; Assign
제목: Re: [hufslion/hufslion.github.io] 예비 세션 자료 업로드 기한 (교육 운영진 5인) (#12)

세션_8전까지 제출 의견 동의합니다.1

**Comment by lee-sj** [comment]
( @hufsglobal ) @meuheuhe 해당 이슈 확인후 먼저 제출하는 2인의 작업에 대한 이슈를 생성해주세요 해당 이슈 종료합니다. 이슈 라벨 세션으로 해도 좋습니다.

**Comment by lee-sj** [comment]
@meuheuhe  작업이 진행되지않아 다시 오픈합니다. 작업 진행해주세요 작업시작하고 이슈 닫아주세요

**Comment by lee-sj** [comment]
@meuheuhe  근거 없이 작업이 계속 딜레이되면 주의 부여하겠습니다. 
작업진행해주세요

**Comment by meuheuhe** [comment]
제가 오늘 오전까지 시험이있어서 늦을 수 있다고 말했었는데요. 집가서 작업하겠습니다

2019년 3월 3일 (일) 13:49, leesj <notifications@github.com>님이 작성:

**Comment by lee-sj** [comment]
@meuheuhe  이슈 생성이라 5분이면 되는 작업입니다.
이슈별로 작업진행되니 이슈별로 답변과 내용 구별해주세요

**Comment by meuheuhe** [comment]
네넵 집가자마자 바로 이슈 만들겠습니다

2019년 3월 3일 (일) 13:58, leesj <notifications@github.com>님이 작성:

**Comment by lee-sj** [comment]
예비 세션 이슈가 생성되서 해당 이슈 닫습니다.
