### ISSUE TITLE
7기 모집 관련 마지막 포스팅

### ISSUE THREAD

**Issue by 16LeeSeul** [hufslion/hufslion.github.io#13]
모집 일주일 전에 마지막 포스팅을 할 계획입니다!!
포스팅 내용은 전 기수에게 물어보는 멋사에 대해 궁금한 점!! 입니다.
각 질문에 2명에서 3명정도로 답해주시면 좋을 것 같습니다.
(혹시 몰라서 대충 질문에 답변 대상자를 정해두었습니다!! 우선6기 기준이고, 5기분들도 자유롭게 후기를 말씀해주세요!!ㅎㅎ)
질문은 에타에 주로 올라오는 질문이나 참고하면 좋을 내용으로 생각해보았습니다.
혹시 더 추가했으면 좋겠다싶은 질문이 있다면 코멘트 달아주세요!!
적어도 내일밤까지는 작성해주시기 바랍니다!!

1.  학업과 병행하면서 웹 프로그래밍을 배우기에는 벅차지 않을까요...?  (은진, 태훈)
2.  비전공자로서 고충은 없었나요!? 비전공자들의 후기를 듣고 싶어요!! (효진, 승윤)

**Comment by meuheuhe** [comment]
네넹

2019년 2월 27일 (수) 21:45, leesj <notifications@github.com>님이 작성:

**Comment by lee-sj** [comment]
1. CSE (컴퓨터공학과) 로 전공자라고 할수있지만 학교에서는 C, C++,JAVA 등을 사용해 알고리즘, 네트워크 구조와 관련 수학이론의 기본적인 것들만 배워서 해당 기술을 가지고 내가 어떻게 취직을 할지 어떻게 활용을 할지 알수 없었는데 멋사를 통해서 Coding 을 하는 개발자 중에서 WEB 분야에서 어떻게 일을 하는지를 알수있었고, 진로(관련직종)에 대해서 좀더 구체적인 경험을 할수있었습니다. 

답변이 좀 딱딱한거 같은데....;; 일단 나중에 좀더 재밌거나 좋은답변이 생각나면 수정하겠습니다!!

**Comment by meuheuhe** [comment]
지금제가 밖이러 저세히 안읽어지는데 내일 함 봐드려도되겠습니가

2019년 2월 27일 (수) 21:58, leesj <notifications@github.com>님이 작성:

**Comment by 16LeeSeul** [comment]
넵!!! 감사합니다ㅎㅎ
네엡 오늘 함 봐주시지욬ㅋㅋㅋㅋㅋ

**Comment by bbj0423** [comment]
1. 확실히 대학생인 입장에선 동아리 활동 보다도 학점이 우선사항이 되게 되고 또 하다보면 순간 내가 학교 공부보다 동아리 공부 때문에 더 스트레스를 받게 된다고? 라는 생각이 들 수도 있습니다. 그러나 이러한 점을 겪으면서 추후에 이제 코딩을 한글자 한글자 치면서 내가 원하는 대로 결과물을 만들어내는 그 때가 됬을 때 그때의 만족감과 희열감은 앞에서 겪은 스트레스를 충분히 보상해줄 만큼 값진 거라고 생각이 됩니다! 
2. 일단 비전공자 입장에선 정말 1도 몰라서 매우 두껍고 큰 문을 만나서 답답함과 내가 과연 이걸 할 수 있을까? 라는 두려움이 생기기도 합니다. 하지만 마음을 편하게 먹고 차근차근하다보면 프로그램 문자를 이해하고 있는 자기 자신을 발견 하게 될 것입니다. 그리고 비전공자 경우 전공자와는 또 다른 다양한 방법을 생각해내거나 시야를 가지고 있는 경우도 있어서 비전공자도 전공자 못지않게  프로그래밍과 친해줄 수 있습니다!!

**Comment by TaeHun-Lee** [comment]
1. 학업과 병행이 가능합니다! 멋사의 근본적 목표는 Web이라는 개념에 대해서 비전공자들도 진입 장벽을 느끼지 않도록 쉽게 접근할 수 있도록 하는 것이기 때문에, Session 자체의 난이도가 높지 않은 편입니다. 오히려 스스로 Session 내용 이상으로 파고드는 사람도 꽤 있는 편입니다ㅡ사실 여기서 시간을 뺏기는 경우도 은근히 많습니다, 마약 같은 Coding의 재미란 도대체...ㅡ. 어차피 Session 진행자도 Session 수강자도 모두 다 같은 대학생입니다. 서로가 서로의 상황을 잘 알기 때문에 스트레스가 되는 선을 넘지 않습니다. 물론 Coding이 명백히 고된 작업입니다. 그러나 멋사는 이미 고된 Coding을 덜 고되게 하고 싶은 동아리라는 것입니다.

2. 저는 소수 언어 전공자입니다. 제 나름 어렸을 적부터 외국어를 많이 좋아하는 편이었고 과에서도 성적을 꽤 잘 받은 편입니다. 전공 언어 나라에서 연수와 인턴까지 하고 왔으니, 솔직히 말하자면 그대로 트랙을 따라가다 졸업만 하면 되는 상황이었습니다. 그러다 우연히 멋사에 대해 알게 되었고, 멋사에 지원하여 우연히 합격했습니다. 그리고 얼마 지나지 않아서 제 이중 전공은 경영에서 컴퓨터로 바뀌어 있었습니다. 비전공자로써 처음에는 두렵기도 했지만, 일단 제 마음가짐은 간단했습니다. '어차피 컴퓨터 언어도 언어의 일종이니, 자연어를 잘 하는 나도 잘 할 수 있을 것이다.' 물론 완전히 맞는 말은 아니지만 지금도 어느 정도는 그 때의 이 마음가짐으로 컴퓨터를 배우고 있습니다. 컴퓨터와 대화한다는 것은 생각보다 흥미롭고 인상적인 일입니다. 마치 외국어를 하며 그 나라 친구를 사귀듯, 멋사로 시작하여 저는 컴퓨팅 언어를 통해 컴퓨터와 친구가 되어가고 있습니다.

**Comment by hyojin17** [comment]
2. 처음에는 내가 코딩이라는 것을 잘 이해하고, 배울수 있을까? 코딩은 전공자들만 할 수 있지 않을까라는 막연한 두려움이 앞섰습니다. 그리고 저는 공부를 할떄도 이해하는 속도가 느린 편이기 때문에, 처음에는 따라가기 속도가 느렸던 것 같아요. 하지만 운영진 분들께서 질문에도 잘 답해주시고, 모르는 것이 있다면 직접 실행해보고 알려주시기 때문에 배우는데에 있어서 큰 어려움이 없었습니다. 그렇게 하나하나씩 배워나가면서 점점 나도 할 수 있다는 마음가짐을 가지면서 배우는 것에 대해 두려움이 사라졌고, 더 열심히 하면 나도 할 수 있구나 라는 것을 느끼게 되었습니다. 그리고 멋쟁이 사자처럼에서는 이론만을 배우는 것이 아니라, 이론을 베이스로 실제 기능들을 구현하는 것을 배우기 때문에 그 기능들이 어떤 것으로 인해서 이렇게 흘러가고, 결과는 이렇게 실행된다 라는 흐름을 실제로 보고, 실행할 수 있어서 코딩에 대한 이론적인 큰 지식과 바탕이 없이도 알려주는 것만으로도 충분히 이해할수 있었습니다. 그리고 멋쟁이 사자처럼을 하면서 이루어나갈수 있는 것이  제가 하고싶었던, 만들고 싶었던 것들을 실제로 프로그래밍을 통해 웹서비스로 만들수 있다는 것이 정말 큰 목표이자 원동력으로 다가와서 열심히 할수있었습니다.  그래서, 막연한 두려움보다, 나도 배울수 있다는 생각을 가지고 임하게 되면 자신 나름대로의 목표를 이룰 수 있었고, 앞으로도 웹프로그래밍을 통해서 여러가지를 도전할 수 있는 기회를 가지게 되었습니다.

**Comment by eunjin97** [comment]
Q. 학업과 웹프로그래밍 병행하기 어렵지 않을까요?

A. 물론 그렇게 생각이 들 수 있지만 일단 사람마다 느끼는 부담감이 다를 것 같습니다.

저 같은 경우는 시험기간 때 학업에 집중적으로 올인하는 스타일이라 멋사는 시험기간 2주동안은 세션과 과제가 없어 크게 부담스럽진 않았어요!

그리고 과제도 세션을 열심히 듣고 임했다면 오래 걸리거나 엄청 어려운 수준이 아니기 때문에 누구나 할 수 있고 복습하는 정도의 수준이어 크게 부담스럽진 않았습니다! 

하지만 사람마다 다를 수 있기 때문에 확답은 드리기 어려울 것 같네요ㅠㅠ..

**Comment by seungyuns** [comment]
2. 비전공자로서 고충은 없었나요!? 비전공자들의 후기를 듣고 싶어요!!

  문과 출신인 저는 고등학교 졸업 이후 수학에 완전히 손을 떼고, 컴퓨터와 저는 앞으로 아무런 관련이 없으리라 생각했습니다. 하지만, 우연히 ‘멋쟁이 사자처럼’을 접하게 되었고 ‘비전공자’를 위한 교육이 이루어진다는 말 하나만 믿고 지원을 하게 되었습니다. ‘비전공자’로서 바로 웹 프로그래밍을 배운다는 것이 쉽지만은 않았지만, 열정적으로 가르치는 학교 운영진의 도움을 받고, 제공되는 온라인 강의들을 듣다 보니, 이것이 꼭 불가능한 일은 아니라는 것을 깨닫게 되었습니다. 또한, 지루한 이론공부만을 진행하는 것이 아니라, 웹 개발을 직접 하면서 이론들이 어떻게 적용, 활용되는지 확인할 수 있기 때문에 재미있게 프로그래밍을 배울 수 있었습니다. ‘멋쟁이 사자처럼’ 활동은 단순히 지식을 전달해주는 것이 아니라, 내가 부족한 부분과 필요한 부분을 찾아내고, 또 스스로 채워 나갈 수 있는 능력을 기를 수 있다는 점에서 특히 ‘비전공자’에게 의미가 깊은 것 같습니다.

**Comment by lee-sj** [comment]
이슈 닫습니다.
