### ISSUE TITLE
면접대기실 안내 PPT

### ISSUE THREAD

**Issue by lee-sj** [hufslion/hufslion.github.io#14]
7기 모집 파일의 면접 일정의 하단에 있는 대기실에 띄워둘 안내사항과, 면접시간과 인원이 적힌 표가 포함된 간단한 ppt의 제작
* 면접 인원표는 이후에 채워넣게 비워진 작업 ppt 

@davidkunin @16LeeSeul  정보팀 해당 작업 면접일 일주일 전까지 마무리해주세요

**Comment by 16LeeSeul** [comment]
넵!!! 이번 주말까지 만들어서 올리도록 하겠습니다!!

**Comment by lee-sj** [comment]
너무 하는거 많은데 이건 면접 한 2~3일 전까지만 해도 괜찮습니다.
피드백 많이 없을것 같습니다 !!!
무리하지말고 쉬어가면서 하세욥 @16LeeSeul

**Comment by 16LeeSeul** [comment]
![kakaotalk_20190304_042719822](https://user-images.githubusercontent.com/37537330/53735098-43e5e800-3ec9-11e9-940a-bdee27812b45.png)
우선 대충 이런 형식으로 생각해보았습니다!!
면접 인원이 정해지는대로 다시 수정해서 올리도록 하겠습니다!!

**Comment by lee-sj** [comment]
저는 좋은것 같습니다.
대기실에 띄워둘것은 간단하게 좋은것 같습니다. 
교육팀장 @meuheuhe  피드백 해주세요

**Comment by meuheuhe** [comment]
전에 말했던 부분이 잘 들어간 것 같습니다

2019년 3월 4일 (월) 22:18, leesj <notifications@github.com>님이 작성:

**Comment by lee-sj** [comment]
이슈 닫겠습니다. 빠른 확인 감사합니다.
