### ISSUE TITLE
Likelion code commit 규칙

### ISSUE THREAD

**Issue by lee-sj** [hufslion/hufslion.github.io#17]
해당 레포의 커밋 규칙은 따로 정하지 않았는데 
커밋 규칙이 필요 하다고 생각합니다. 
해당의견에 대한 피드백 해주세요
@hufslion/cap

**Comment by meuheuhe** [comment]
세션 번호 까지 적고 해당 강의 내용 제목정도 적는게 좋을것 같습니다

**Comment by lee-sj** [comment]
지금 있는 상황에서 크게 뭔가를 새로 만들필요는 없겠죠? 
하던데로 조금 깔끔한제목정도로?
@meuheuhe

**Comment by meuheuhe** [comment]
네 해당 내용만 알 수 있을정도로만 해도 괜찮을 것 같습니다.

**Comment by 16LeeSeul** [comment]
네 동의합니다!! 아 제목 조건정도...?
세션 번호(세션 진행 날짜)-세션 주제 -세션자명
이런 제목 알아보기 쉽게 형식만 맞추는 정도!? 이면 좋을 것 같스니다!!

**Comment by lee-sj** [comment]
옙 
세션 번호(세션 진행 날짜)-세션 주제 -세션자명 
이렇게 간단히 하고 
현상유지 하는게 좋을것 같습니다!!!
