### ISSUE TITLE
세션_2 자료 업로드 (성준)

### ISSUE THREAD

**Issue by lee-sj** [hufslion/hufslion.github.io#20]
세션 관련 세부사항 @lee-sj 제가 직접 이야기 해왔어서 
세션 2 자료는 제가 받아서 바로 공유 하겠습니다.

**Comment by lee-sj** [comment]
해당 세션 분량은 2시간으로 잡고있다고 합니다.
세션 1과 세션2 원활한 소통을 위해서 콜라보레이터로 자룡형님 초대하겠습니다.

**Comment by lee-sj** [comment]
@kujarung 자료 진행상황 공유부탁드립니다

**Comment by lee-sj** [comment]
@kujarung  자료 진행상황 / 딜레이 원인등 모두가 볼수있게 공유해주세요 ~!!

**Comment by kujarung** [comment]
[hufsppt2.pptx](https://github.com/hufslion/hufslion.github.io/files/2949686/hufsppt2.pptx)

https://github.com/kujarung/css_project

근래에 야근이 좀 많아 자료 만드는 데 시간이 좀 걸리고 있음
약 60페이지 정도에 PPT 준비 중이고 지금 까지 작업 한 내용을 올림

3월 13일 까지 완성해서 다시 올릴 예정
기본적인 CSS 사용법(font , margin , padding , background-image , float , position)을 강의 할 예정이고
예제나 실습은 기존에 익숙한 버튼이나 형태를 따라서 만들 예정이라 만드는 데 조금 시간이 생각 보다 오래 걸리고 있음

**Comment by lee-sj** [comment]
http://hufsglobal.likelion.org/1st-session/ 
사이트 업로드용 자료 예시 입니다 이전 세션인 세션 1 자료입니다.
참고해서 만들어주세요 
해당 링크 하단부에 세션용 ppt 도 있습니다 참고해서 
[템플릿.pptx](https://github.com/hufslion/hufslion.github.io/files/2950819/default.pptx)
이 템플릿 ppt 적용해서 ppt 만들어주세요
세션 3에서 처음으로 git을 설명하는데 자료에 git clone 하는것이 있던데 아직 설명전이니 일단 따라서 치는걸로 하고 넘어가는것이 좋겠네요

https://github.com/hufsglobal/hufsglobal.github.io 해당 테스트 서버에서 자유롭게 푸시 해서 테스트 해도 무방합니다.  해당 레포지토리에 콜라보 추가 해두었습니다.

**Comment by kujarung** [comment]
https://github.com/kujarung/css_project/blob/master/pro.md

[default.pptx](https://github.com/hufslion/hufslion.github.io/files/2962156/default.pptx)

1차 완성본

이론은 최대한 빼고 실습 위주로 넣어서 구성함
실습 코드는 완성 되었으나 가다듬어야 할 부분이 많아 아직 제작 중에 있어 완성 이미지만 넣어둠
(코드잇이라는 강의 여러 자료 참조)

**Comment by lee-sj** [comment]
깃헙 내부 md 와 Jekyll 문법이 조금달라서 달게 보일수있으니 github.com/hufsglobal/hufsglobal.github.io 에서 실제로 테스트후 최종업로드를 이곳에 해주세요 내용은 좋아보입니다

**Comment by 16LeeSeul** [comment]
![image](https://user-images.githubusercontent.com/37537330/54332627-fbad8f00-4659-11e9-9701-3a733a05b6c8.png)
형광펜 부분 class 오타난 것 같습니다!!! 내용 완전 좋아요!!!

**Comment by lee-sj** [comment]
https://github.com/hufsglobal/hufsglobal.github.io/invitations 
hufsglobal 테스트 블로그 초대 수락 안하셨길래 링크 첨부합니다. 여기서 블로그 포스팅 해보고 화면 어떻게 나오시는지 직접 보는게 더 수정하는데 편할것 같습니다.

**Comment by lee-sj** [comment]
@kujarung
세션 시작 5일도 안남았습니다
 md 자료 pr 해주세요

**Comment by lee-sj** [comment]
이슈 닫습니다
