### ISSUE TITLE
예비 세션 자료 업로드(윤서, 승윤)

### ISSUE THREAD

**Issue by meuheuhe** [hufslion/hufslion.github.io#22]
예비세션 자료 업로드는 15일까지 해주시면 되겠습니다.

(세션 자료 업로드 하는 방법은 wiki를 참고하시면 되고, 자료는PR 해주시면 됩니다.)

**Comment by lee-sj** [comment]
테스트는 테스트서버에서 하고 작업완료본만 pr보내주세요 
작업전에 자료 주제 코멘트 남겨주세요

**Comment by lee-sj** [comment]
@bbj0423  @seungyuns  준비중인 세션 내용 코멘트 남기고 작업해주세요

**Comment by lee-sj** [comment]
@bbj0423 @seungyuns 관련 작업 무응답 일시 주의 부여합니다. 
( @meuheuhe , @16LeeSeul )

**Comment by seungyuns** [comment]
신승윤 -> VS코드로 페이스북구현하기 작업하겠습니다. (기본 CSS, CRUD, 댓글기능)

**Comment by bbj0423** [comment]
장윤서 -> 주제 : djnago cookiecutter 사용법과 text editor 적용하기 입니다!

**Comment by lee-sj** [comment]
@seungyuns  정규 세션 내용과 다른 세션 준비 해주세요 
@16LeeSeul  @meuheuhe  팀장님들 해당 세션 내용 어떻게 생각하시나요

**Comment by 16LeeSeul** [comment]
앗 네!! 정규 세션과 내용이 겹치는 것 같습니다.
조금 다른 주제로 선정하셔야 할 것 같습니다!!

**Comment by lee-sj** [comment]
@meuheuhe 의견주시면 확인하고 같은 의견이면 주제 변경 요청하려고 합니다.
확인하시고 코멘트 남겨주세요

**Comment by meuheuhe** [comment]
복습겸 해서 후반부에 하면 괜찮을듯 하지만 초반에 하기엔 이른감이 있다고 생각이 드네요.

**Comment by lee-sj** [comment]
@seungyuns  전반부 세션 공백 대비 예비 세션진행자 여서 해당 세션 주제에 변경이 필요합니다. 
다른 주제를 선정해서 작업 진행해주세요

**Comment by lee-sj** [comment]
@meuheuhe 승윤이 자료 제출기한 수정해서 다시한번 코멘트해주세요

**Comment by meuheuhe** [comment]
다음주 금요일로 미루겠습니다.

**Comment by meuheuhe** [comment]
이번주 금요일까지 예비세션 자료 pr 해주시면됩니다.

**Comment by seungyuns** [comment]
넵 확인했습니다.

**Comment by lee-sj** [comment]
@seungyuns  @bbj0423  수정사항 있습니다.

**Comment by seungyuns** [comment]
넵 확인하겠습니다.

**Comment by meuheuhe** [comment]
예비세션 오늘까지 pr 해주시길 바랍니다.

**Comment by lee-sj** [comment]
@bbj0423
예비세션 자료 ppt 링크 링크 이름짧게만들어서 다시 푸시해주세요
다른내용 모두 확인했습니다

**Comment by meuheuhe** [comment]
세션자료 확인했으니 이슈 닫겠습니다.
