### ISSUE TITLE
세션_3 자료 업로드(효진)

### ISSUE THREAD

**Issue by meuheuhe** [hufslion/hufslion.github.io#23]
세션 3 자료 다음 주 월요일 11일 까지 업로드 부탁 드리겠습니다.
내용은 파이썬 기본문법1(연산 , 반복/조건문, 튜플, 리스트, 딕셔너리)
부트스트랩 사용하기(CDN) - 게시판에 사용하는 form, card등 grid, glyphicon
github Page 만들기, git 명령어

(세션 자료 업로드 방법은 wiki를 참고하시면 되고, 자료는 Pull Request 해주시면 됩니다.)

**Comment by hyojin17** [comment]
넵!! 깃헙 페이지 만들기는 우리가 사용하는 깃헙페이지를 말하는 건가요??

**Comment by lee-sj** [comment]
@hyojin17 깃헙 페이지 만들기가 jekyll 블로그를 만드는것을 의미하는것이 아닌 일반 html  static 파일을 올려서 USERNAME.github.io 의 본인 사이트를 만드는것을 의미합니다.

**Comment by hyojin17** [comment]
@lee-sj   넵!! 감사합니다!

**Comment by hyojin17** [comment]
부트스트랩4부터는 glyphicon이 사라졌다고 합니다. 이 없어진 기능은 제외해도 되나요?

**Comment by lee-sj** [comment]
@hyojin17 pr이 정상적이지않아 닫았습니다 확인하고 다시 pr 주세요

**Comment by lee-sj** [comment]
@hyojin17 ppt 와 자료 모두 고생 많았어요!!! 모두 확인하고 머지 했습니다. 이슈 닫겠습니다.
