### ISSUE TITLE
논의 필요 이슈입니다. 

### ISSUE THREAD

**Issue by lee-sj** [hufslion/hufslion.github.io#26]
포스팅이 마무리 후 포스팅 순서에 따라서 게시글의 순서가 정해지는데 게시글 순서를 정리하려면 
이후에 파일의 제목을 세션일로 수정하면 좋을것 같습니다. 
다른 의견있으신가요
( 현재 http://hufsglobal.likelion.org/session/ 를 확인해보면 OT를 더 늦게 완료해서 순서가 바뀐것으로 보아 앞으로 이상황이 지속된다면 계속해서 순서가 엉망이 될것 같습니다. )

그리고 두번째 이슈는 현재 session 페이지를 root 페이지에서 이동할수 없고 url 입력으로만 접근이 가능한데 해당 링크를 외부인이 볼수도있는 root에 넣어햐 하는지 에 대한 논의입니다. 
( 제 개인적인 판단으로는 root 에서 session 으로 접근할수있는 버튼이나 링크를 생성하지 않았으면 합니다. ) 

@16LeeSeul  @meuheuhe

**Comment by meuheuhe** [comment]
세션일로 한다는게  날짜만 넣는다는건가요 두 번째는 링크가 따로 없으니 누가 알고있는게 아니라면 그렇게 문제가 있을까 하는 생각입니다.

2019년 3월 6일 (수) 오후 1:59, leesj <notifications@github.com>님이 작성:

**Comment by lee-sj** [comment]
파일명을 바꾸어서 순서를 조정하는게 좋겠다는 뜻입니다. 
지금 사이트 보면 OT 자료가 세션 1보다 더 늦게 업로드 되어서 더 위에 있는상황인데 앞으로 자료 완성 순서가 꼬인다면 해당 상황보다 더 복잡하게 순서가 뒤죽박죽일것같아서 파일명을 그때그때 세션일로 변경하는것이 어떤가입니다. 날짜만 넣는다면 순서는 그대로 뒤죽박죽일테니 크게 의미있는 변경은 아닌것 같습니다. 

문제가 있다는것이 아니라 root 에 링크를 삽입하느냐 삽입하지않느냐의 선택사항에 대한 논의입니다.

**Comment by meuheuhe** [comment]
root에 링크를 굳이 넣을 필요는 없을거 같긴합니다.

**Comment by seungyuns** [comment]
순서 조정이 깔끔할 것 같습니다. root는 삽입 안해도 상관없을 것 같습니다.

**Comment by lee-sj** [comment]
예 알겠습니다 관련 업무 규정 새로 생성하겠습니다. 
이슈 마무리 하겠습니다.
