### ISSUE TITLE
세션_5,6 자료 업로드(건, 윤서)

### ISSUE THREAD

**Issue by meuheuhe** [hufslion/hufslion.github.io#32]
세션 5, 6 자료 다음 주 목요일(21일) 까지 업로드 부탁 드리겠습니다.

세션 5
로또 번호 답 공개(가장짧게) 메소드 이용
HTTP Method 종류
method -get을 이용한 Word Count 페이지 만들기 (값을 보냈을 때 Url확인과, 데이터 전송)

파싱, 크롤링 이란?
파이썬으로 파싱하기
실제사이트 파싱해보기 ex) 로또 값

세션 6
Queryset
method - Post 게시판 만들기
Create, Read

장고어드민 페이지를 이용해 글 추가해보기(createsuperuser)
pk, path converter
get_object_or_404

(세션 자료 업로드 방법은 wiki를 참고하시면 되고, 자료는 Pull Request 해주시면 됩니다.)

**Comment by meuheuhe** [comment]
확인하셨으면 커멘트 해주세요.

**Comment by davidkunin** [comment]
확인했습니다~

**Comment by bbj0423** [comment]
확인했습니다

**Comment by bbj0423** [comment]
지금 다시금 생각해봤는데 제가 모델부분도 세션에 포함해야되겠죠? 앞에 분들 세션중에 모델 언급할 세션없겠죠?

**Comment by meuheuhe** [comment]
너 앞에까진 모델 안건들고 윤서부터 어드민페이지 다루면서 모델 만질듯한데 워드카운트면 모델 필요 없을듯!

**Comment by bbj0423** [comment]
형.. 나 윤서야... davidkunin  이게 건이야... 우리 좀만 더 친해져야겠다...

**Comment by meuheuhe** [comment]
아하.. 방금까지 건이랑 말하느라 순간.. 그렇다면 당연 모델해야지

**Comment by bbj0423** [comment]
오케이~

**Comment by davidkunin** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ웃기네

**Comment by bbj0423** [comment]
기한까지 제출하지 못하여 주의 1스택 받겠습니다

**Comment by meuheuhe** [comment]
네 알겠습니다. 그러면 다음주 금(29일) 까지 세션6,7까지 해주시면 되겠습니다.

**Comment by meuheuhe** [comment]
이슈 닫겠습니다.
