### ISSUE TITLE
[정보팀] OT 사진

### ISSUE THREAD

**Issue by 16LeeSeul** [hufslion/hufslion.github.io#33]
오늘 학교 OT 때 참석해서 사진 찍어주시고, 곧 공유될 드라이브 활동사진 폴더에 올려주세요!!

전체 OT 때는 제가 사진 찍어서 올리겠습니다!!

**Comment by lee-sj** [comment]
@hufslion/operator 7기 공유 드라이브 금요일에 공유 할 예정입니다. 
우선 7기 폴더가 아닌 우선 운영진 폴더에 업로드해주세요

**Comment by lee-sj** [comment]
이슈 닫습니다.
