### ISSUE TITLE
7기 모집 포스터

### ISSUE THREAD

**Issue by lee-sj** [hufslion/hufslion.github.io#5]
사이트에 
글 제목 '7기 모집 포스터' 로 포스터 업로드 해주세요

**Comment by lee-sj** [comment]
![pic](https://user-images.githubusercontent.com/30469948/53099914-22e8d300-356a-11e9-9cb5-fc04f0720682.jpg)
포스터 업로드 합니다.

**Comment by lee-sj** [comment]
@meuheuhe 모집포스터 게시글 업로드 해주세요

**Comment by hufsglobal** [comment]
@meuheuhe  포스터 사이트 업로드 늦어서 의미 없을것 같습니다. 추가 작업 없이 이슈 닫습니다. ㅡㅡ;

**Comment by meuheuhe** [comment]
지금도 충분히 깔끔하고 보기좋아서 수정안해도 괜찮은듯 합니다

2019년 2월 28일 (목) 15:41, hufsglobal <notifications@github.com>님이 작성:

**Comment by lee-sj** [comment]
@meuheuhe  포스터 업로드 안되있는데 무슨뜻인가요

**Comment by meuheuhe** [comment]
아 세부사항 정도로만 생각하고 있었는데 그러면 멋사 기본 포스터 업로드 하면 될가요?

2019년 2월 28일 (목) 오후 3:46, leesj <notifications@github.com>님이 작성:

**Comment by lee-sj** [comment]
@meuheuhe 모집 초반에 올렸어야 했는데 늦었다고 생각하는데 사이트(hufsglobal.likelion.org) 확인하고 포스터 업로드가 필요하다고 생각하면 업로드 해주세요

**Comment by meuheuhe** [comment]
그리고 어제 물어본 자소서라고 해야되나 한 번 생각해보고 써보았습니더
언어들을 사용해 알고리즘, 네트워크 구조에 대한 것들을 배웠었지만, 취업을하고 실무에는 이런 기술들을 어떻게 활용하는지 자세히 알 수
없었는데, 멋사 활동을 통해 웹개발을 할 때 어떻게 일이 진행되는지 몸으로 느낄 수 있었고 제 인생에서 가장 중요한 터닝 포인트가
되었던 것 같습니다.

2019년 2월 28일 (목) 오후 3:51, leesj <notifications@github.com>님이 작성:

**Comment by meuheuhe** [comment]
음.. 개인적으론 포스터가 마음에 안들어서 7기 모집 글만으로도 충분하다고 생각하는데 어떻게 생각하십니까

2019년 2월 28일 (목) 오후 3:52, 김기중 <rlarlwnd61@gmail.com>님이 작성:

**Comment by hufsglobal** [comment]
@meuheuhe 이슈에 맞게 comment 남겨주세요 여기는 모집 포스터 관련 이슈입니다. 
후기 업로드 게시글 관련 내용 해당 이슈로 이동해주세요 
저는 포스터 지금 올리는것 의미없다 판단하여 추가 작업 없는것으로 이슈 닫았습니다.

**Comment by meuheuhe** [comment]
네넵 알겠습니다 그러면 저기 이슈에 맞지 않는 글은 다시 그 전 답장에 달겠습니다.

2019년 2월 28일 (목) 오후 3:58, hufsglobal <notifications@github.com>님이 작성:
