### ISSUE TITLE
세션_4 내용 추가(은진)

### ISSUE THREAD

**Issue by meuheuhe** [hufslion/hufslion.github.io#53]
로또생성 알고리즘을 짜기위해
메소드 사용 방법에서 예시로 로또과제에 필요한 메소드 들도 추가 해주시면 됩니다.
ex)
import random

num = random.randrange(1, 11) # 1부터 10 사이의 난수 생성
num2 = random.randrange(1, 11, 2) # 1부터 10 사이의 난수(홀수) 생성
print(num) 
print(num2)
등의 추가와 
세션 5에서 로또 번호와 비교해서 몇 개 맞았나 확인을 위한 find, in 
ex) 
a = range(10)
 5 in a
 16 in a

>>> a = "Python is the best choice"
>>> a.find('b')
14
>>> a.find('k')
-1

이번주 일요일(24일) 까지 해주시면 됩니다.

**Comment by eunjin97** [comment]
넵 알겠습니다.

**Comment by meuheuhe** [comment]
이슈 닫겠습니당.
