### ISSUE TITLE
세션_8 자료 업로드(승윤)

### ISSUE THREAD

**Issue by meuheuhe** [hufslion/hufslion.github.io#58]
세션 8자료 이번 주 일요일(31일) 까지 업로드 부탁 드리겠습니다.
내용은 템플릿 상속 및 활용(base.html , static 디렉토리에 정리 등)
            Urls 관리(include 사용) 되겠습니다.

**Comment by seungyuns** [comment]
네. 확인했습니다.

**Comment by lee-sj** [comment]
@seungyuns  session 폴더의 4th 폴더를 리네임해서 pr 해주세요 파일 생성하지마시구요

**Comment by seungyuns** [comment]
넵.

**Comment by seungyuns** [comment]
@meuheuhe @lee-sj 8th 세션자료 pr보내드렸습니다. 확인 부탁드려요.

**Comment by lee-sj** [comment]
@seungyuns 코딩데이랑 회식 끝나고 바로 pr 확인하고 리뷰 했습니다!!!

**Comment by seungyuns** [comment]
@meuheuhe  @lee-sj  확인했습니다. 일단 수정내용 수정하고 대기하고있으면 되나요??

**Comment by meuheuhe** [comment]
이슈 닫습니다.
