### ISSUE TITLE
세션_5 자료 내용 확인 (건)

### ISSUE THREAD

**Issue by davidkunin** [hufslion/hufslion.github.io#61]
2019-4-01-5th-session.md 내용 확인 부탁드립니다.

**Comment by lee-sj** [comment]
오늘은 12시가... 자정..... 내일 보고 코맨트남길게요

**Comment by lee-sj** [comment]
폰으로 봐서그런지 스압이 심한데 자료 2페이지로 분리에 대한 의견을 조심스럽게 남기고 총총총 자러갑니다

**Comment by davidkunin** [comment]
그러면 05-1 / 05-2 이렇게 쪼개서 올려도 괜찮을까요?

**Comment by meuheuhe** [comment]
노트북이나 모니터로 확인했을 때는 괜찮은듯합니다.

**Comment by lee-sj** [comment]
안나눠도 상관 없다면 그대로 갑시다 제가 말씀드린 오타도 수정 이미 하셨네요 확인했습니다.

**Comment by lee-sj** [comment]
추가확인 2일동안 업어서 닫겠습니다. 이대로 가죠
