### ISSUE TITLE
운영진 작업 과정에 대한 피드백

### ISSUE THREAD

**Issue by lee-sj** [hufslion/hufslion.github.io#62]
피드백 남겨주세요

**Comment by seungyuns** [comment]
다들 깃헙 블로그를 사용하는게 처음이고 익숙하지 않아서 시행착오가 많았던거 같습니다. 어느정도 적응기간이 필요할 듯.

**Comment by TaeHun-Lee** [comment]
지금은 사이클이 익숙하지가 않아서인지 살짝 이러저러 헷갈리는듯 합니다

**Comment by hyojin17** [comment]
사용하는게 아직 적응되지않아서 헷갈리는게 많은것같습니다. 여러번 겪어보면 익숙해질듯합니다.

**Comment by bbj0423** [comment]
다들 처음이라 그런거지 사용해서 익숙해지면 확실히 좋은듯

**Comment by davidkunin** [comment]
시스템이 익숙하지 않아서 조금 헤맸습니다. 적응되면 좋은 시스템일 것 같습니다.

**Comment by lee-sj** [comment]
좀더 자세한 위키와 유저 친화적인 시스템으로 좀더 손보도록 하겠습니다. 의견 감사합니다

**Comment by lee-sj** [comment]
@hufslion/operator  금요일에 이슈 닫겠습니다. 그때까지 피드백 주세요

**Comment by eunjin97** [comment]
위의 분들과 같은 의견입니다!
