### ISSUE TITLE
세션_14 자료 업로드(승윤)

### ISSUE THREAD

**Issue by meuheuhe** [hufslion/hufslion.github.io#90]
세션 14 자료 5월 9일(목요일) 까지 업로드 부탁 드리겠습니다.
내용은 로그인 구현과 로그인 했을 때 authentication을 통해 인증 및 권한 부여, 
(참고 : https://docs.djangoproject.com/en/2.2/topics/auth/default/)
Faker 입니다.

**Comment by meuheuhe** [comment]
업로드날짜 수정했습니다.

**Comment by lee-sj** [comment]
해당 내용도 머지 완료해서 바로 이슈 닫겠습니다.,
